baseURL = 'https://jeongseup.github.io'
title = 'Jeongseup Blog'
theme = 'hugo-coder'
defaultContentLanguage = 'en'
enableEmoji = true
enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 6

[params]
  author = 'Jeongseup'
  info = 'Developer, Cloud Enthusiast, Software Engineer'
  description = "Jeongseup's personal blog on software development, cloud, and technology."
  keywords = 'software, development, cloud, engineering, programming, technology, personal blog, jeongseup'
  avatarURL = 'images/avatar.jpg'
  
  since = 2025
  dateFormat = "January 2, 2006"

  enableTwemoji = true
  colorScheme = 'auto'
  hideFullResImage = true
  commit = "https://github.com/jeongseup/jeongseup.github.io/tree/"

  # Social links
  [[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/jeongseup/"
  [[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/jeongseup/"
  [[params.social]]
    name = "RSS"
    icon = "fa-solid fa-rss fa-2x"
    weight = 3
    url = "https://jeongseup.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[languages]
  [languages.en]
    languageName = "🇬🇧 English"
    title = "Jeongseup Blog"
    weight = 1

    [languages.en.params]
      author = "Jeongseup"
      info = "Developer, Cloud Enthusiast, Software Engineer"
      description = "Jeongseup's personal blog on software development, cloud, and technology."

    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"
    [[languages.en.menu.main]]
      name = "Blog"
      weight = 2
      url = "posts/"
    [[languages.en.menu.main]]
      name = "Projects"
      weight = 3
      url = "projects/"
    [[languages.en.menu.main]]
      name = "Contact Me"
      weight = 4
      url = "contact/"

  [languages.ko]
    languageName = "🇰🇷 한국어"
    title = "정섭 블로그"
    weight = 2

    [languages.ko.params]
      author = "정섭"
      info = "개발자, 클라우드 애호가, 소프트웨어 엔지니어"
      description = "정섭의 소프트웨어 개발, 클라우드 및 기술 블로그."

    [[languages.ko.menu.main]]
      name = "소개"
      weight = 1
      url = "about/"
    [[languages.ko.menu.main]]
      name = "블로그"
      weight = 2
      url = "posts/"
    [[languages.ko.menu.main]]
      name = "프로젝트"
      weight = 3
      url = "projects/"
    [[languages.ko.menu.main]]
      name = "연락하기"
      weight = 4
      url = "contact/"
